name: JW_Piano
version: ${project.version}
main: jw.piano.Main
api-version: 1.17
permissions:
  piano:
    description: general piano permissions
    children:
      - piano.remove
      - piano.create
      - piano.volume
      - piano.rename
      - piano.skin
      - piano.active
      - piano.effects
      - piano.update
      - piano.pedal
      - piano.teleport

  piano.remove:
    description: removes piano

  piano.create:
    description: creates piano

  piano.volume:
    description: sets piano's volume

  piano.rename:
    description: sets piano's name

  piano.skin:
    description: sets piano's skin

  piano.active:
    description: sets piano's active or inactive

  piano.effects:
    description: sets piano's effects

  piano.update:
    description: download latest version of plugin

  piano.teleport:
    description: allows player to teleport to piano

  piano.detect-key:
    description: set if players can press keys of certain piano

  piano.desktop-client:
    description: set if players can use dektop app